T = {
    'fr': {
        'hello': 'Bonjour',
        'contact': 'Pour toute question, contactez-nous à {email}.',
        'regards': 'Cordialement,',
        'team': "L'équipe {name}",
        'footer': '{name} - Location de véhicules en Suisse',
        'docs_title': 'Documents obligatoires à présenter',
        'docs_id': "Carte d'identité physique (originale, en cours de validité)",
        'docs_license': 'Permis de conduire physique (original, en cours de validité)',
        'docs_warning': 'Sans ces documents, le véhicule ne pourra pas vous être remis.',
        'cat_label': 'Catégorie',
        'pickup': 'Date de prise en charge',
        'ret': 'Date de retour',
        'duration': 'Durée',
        'days': 'jour(s)',
        'location_label': 'Lieu',
        'total': 'Montant total',
        'conf_header': 'Confirmation de réservation',
        'conf_title': 'Réservation Confirmée',
        'conf_text': 'Nous avons le plaisir de vous confirmer votre réservation. Nous vous garantissons le véhicule réservé ou un véhicule équivalent de la même catégorie.',
        'cash_note': 'Le paiement sera effectué en espèces lors de la prise en charge du véhicule.',
        'conf_subject': 'Réservation confirmée - {v} | LogiRent',
        'req_header': 'Demande de réservation',
        'req_title': 'Demande de réservation reçue',
        'req_text': "Nous avons bien reçu votre demande de réservation. Notre équipe va l'analyser et vous envoyer une confirmation dans les plus brefs délais.",
        'req_pending': "Votre réservation est en attente de confirmation par notre équipe. Vous recevrez un e-mail dès qu'elle sera validée.",
        'req_subject': 'Demande de réservation reçue - {v} | LogiRent',
        'offer_header': 'Offre de réservation',
        'offer_sub': "L'agence vous propose une offre pour votre demande",
        'offer_text': 'Après étude de votre demande, notre agence vous fait parvenir une offre pour la réservation du <strong>{v}</strong>.',
        'offer_new_price': 'Nouveau prix proposé',
        'offer_msg_label': "Message de l'agence",
        'offer_accept': 'Pour <strong>accepter cette offre</strong>, connectez-vous à votre espace LogiRent. Si vous ne souhaitez pas donner suite, vous pouvez ignorer ce message.',
        'offer_subject': 'Offre de réservation - {v} - CHF {p:.2f} | LogiRent',
        'pay_header': 'Confirmation de paiement',
        'pay_title': 'Paiement Confirmé',
        'pay_text': 'Nous confirmons la bonne réception de votre paiement. Votre réservation est désormais entièrement validée.',
        'pay_badge': 'Paiement reçu - Réservation validée',
        'pay_subject': 'Paiement confirmé - {v} | LogiRent',
        'rem_header': 'Rappel - Location demain',
        'rem_title': 'Rappel - Votre location commence demain',
        'rem_text': 'Nous vous rappelons que votre location débute <strong>demain le {d}</strong>.',
        'rem_location': 'Lieu de prise en charge : <strong>{loc}</strong>',
        'rem_location_missing': 'Le lieu de prise en charge vous sera communiqué par votre agence.',
        'rem_subject': 'Rappel : votre location de {v} commence demain | LogiRent',
        'st_header': 'Mise à jour de votre réservation',
        'st_confirmed_title': 'Réservation Confirmée',
        'st_confirmed_msg': 'Votre réservation pour <strong>{v}</strong> a été confirmée.',
        'st_active_title': 'Location En Cours',
        'st_active_msg': 'Votre location de <strong>{v}</strong> est maintenant active. Bon trajet !',
        'st_completed_title': 'Location Terminée',
        'st_completed_msg': 'Votre location de <strong>{v}</strong> est terminée. Merci de votre confiance !',
        'st_cancelled_title': 'Réservation Annulée',
        'st_cancelled_msg': 'Votre réservation pour <strong>{v}</strong> a été annulée.',
        'st_update_title': 'Mise à jour',
        'st_update_msg': 'Le statut de votre réservation a été mis à jour.',
        'st_confirmed_subject': 'Réservation confirmée - {v}',
        'st_active_subject': 'Location en cours - {v}',
        'st_completed_subject': 'Location terminée - {v}',
        'st_cancelled_subject': 'Réservation annulée - {v}',
        'st_update_subject': 'Mise à jour réservation - {v}',
        'veh_label': 'Véhicule',
        'from_label': 'Du',
        'to_label': 'Au',
        'amount_label': 'Montant',
        'wel_subject': 'Bienvenue chez {name} - Vos identifiants de connexion',
        'wel_sub': 'Bienvenue sur notre plateforme de location',
        'wel_text': 'Votre compte a été créé avec succès par <strong>{name}</strong>. Vous pouvez désormais vous connecter pour consulter nos véhicules disponibles et effectuer vos réservations.',
        'wel_creds': 'Vos identifiants de connexion',
        'wel_email': 'Email',
        'wel_pass': 'Mot de passe',
        'wel_change': 'Nous vous recommandons de changer votre mot de passe après votre première connexion.',
        'wel_login': 'Se connecter maintenant',
        'wel_mobile': 'Application mobile',
        'wel_scan': "Scannez ce QR code pour accéder à l'application",
        'wel_contact': "Pour toute question, n'hésitez pas à nous contacter.",
        'wel_footer': '{name} — Location de véhicules',
        'ct_header': 'Contrat de location signé',
        'ct_title': 'Contrat Signé avec Succès',
        'ct_text': 'Votre contrat de location <strong>N&deg; {n}</strong> pour le véhicule <strong>{v}</strong> a été signé avec succès.',
        'ct_pdf_text': 'Vous trouverez le contrat signé en pièce jointe de cet email au format PDF.',
        'ct_pdf_badge': 'Le PDF du contrat est joint à cet email',
    },
    'en': {
        'hello': 'Hello',
        'contact': 'For any questions, contact us at {email}.',
        'regards': 'Best regards,',
        'team': 'The {name} team',
        'footer': '{name} - Car rental in Switzerland',
        'docs_title': 'Mandatory documents to present',
        'docs_id': 'Physical ID card (original, valid)',
        'docs_license': "Physical driver's license (original, valid)",
        'docs_warning': 'Without these documents, the vehicle cannot be handed over to you.',
        'cat_label': 'Category',
        'pickup': 'Pick-up date',
        'ret': 'Return date',
        'duration': 'Duration',
        'days': 'day(s)',
        'location_label': 'Location',
        'total': 'Total amount',
        'conf_header': 'Booking confirmation',
        'conf_title': 'Booking Confirmed',
        'conf_text': 'We are pleased to confirm your booking. We guarantee the reserved vehicle or an equivalent vehicle of the same category.',
        'cash_note': 'Payment will be made in cash when picking up the vehicle.',
        'conf_subject': 'Booking confirmed - {v} | LogiRent',
        'req_header': 'Booking request',
        'req_title': 'Booking request received',
        'req_text': 'We have received your booking request. Our team will review it and send you a confirmation as soon as possible.',
        'req_pending': 'Your booking is awaiting confirmation by our team. You will receive an email as soon as it is validated.',
        'req_subject': 'Booking request received - {v} | LogiRent',
        'offer_header': 'Booking offer',
        'offer_sub': 'The agency has an offer for your request',
        'offer_text': 'After reviewing your request, our agency is sending you an offer for the booking of the <strong>{v}</strong>.',
        'offer_new_price': 'New proposed price',
        'offer_msg_label': 'Message from the agency',
        'offer_accept': 'To <strong>accept this offer</strong>, log in to your LogiRent account. If you do not wish to proceed, you can ignore this message.',
        'offer_subject': 'Booking offer - {v} - CHF {p:.2f} | LogiRent',
        'pay_header': 'Payment confirmation',
        'pay_title': 'Payment Confirmed',
        'pay_text': 'We confirm the receipt of your payment. Your booking is now fully validated.',
        'pay_badge': 'Payment received - Booking validated',
        'pay_subject': 'Payment confirmed - {v} | LogiRent',
        'rem_header': 'Reminder - Rental tomorrow',
        'rem_title': 'Reminder - Your rental starts tomorrow',
        'rem_text': 'We remind you that your rental starts <strong>tomorrow on {d}</strong>.',
        'rem_location': 'Pick-up location: <strong>{loc}</strong>',
        'rem_location_missing': 'The pick-up location will be communicated to you by your agency.',
        'rem_subject': 'Reminder: your {v} rental starts tomorrow | LogiRent',
        'st_header': 'Update on your booking',
        'st_confirmed_title': 'Booking Confirmed',
        'st_confirmed_msg': 'Your booking for <strong>{v}</strong> has been confirmed.',
        'st_active_title': 'Rental In Progress',
        'st_active_msg': 'Your rental of <strong>{v}</strong> is now active. Have a good trip!',
        'st_completed_title': 'Rental Completed',
        'st_completed_msg': 'Your rental of <strong>{v}</strong> is completed. Thank you for your trust!',
        'st_cancelled_title': 'Booking Cancelled',
        'st_cancelled_msg': 'Your booking for <strong>{v}</strong> has been cancelled.',
        'st_update_title': 'Update',
        'st_update_msg': 'The status of your booking has been updated.',
        'st_confirmed_subject': 'Booking confirmed - {v}',
        'st_active_subject': 'Rental in progress - {v}',
        'st_completed_subject': 'Rental completed - {v}',
        'st_cancelled_subject': 'Booking cancelled - {v}',
        'st_update_subject': 'Booking update - {v}',
        'veh_label': 'Vehicle',
        'from_label': 'From',
        'to_label': 'To',
        'amount_label': 'Amount',
        'wel_subject': 'Welcome to {name} - Your login credentials',
        'wel_sub': 'Welcome to our rental platform',
        'wel_text': 'Your account has been successfully created by <strong>{name}</strong>. You can now log in to browse our available vehicles and make your bookings.',
        'wel_creds': 'Your login credentials',
        'wel_email': 'Email',
        'wel_pass': 'Password',
        'wel_change': 'We recommend changing your password after your first login.',
        'wel_login': 'Log in now',
        'wel_mobile': 'Mobile app',
        'wel_scan': 'Scan this QR code to access the app',
        'wel_contact': 'For any questions, do not hesitate to contact us.',
        'wel_footer': '{name} — Car rental',
        'ct_header': 'Rental contract signed',
        'ct_title': 'Contract Successfully Signed',
        'ct_text': 'Your rental contract <strong>No. {n}</strong> for the vehicle <strong>{v}</strong> has been successfully signed.',
        'ct_pdf_text': 'You will find the signed contract attached to this email in PDF format.',
        'ct_pdf_badge': 'The contract PDF is attached to this email',
    },
    'de': {
        'hello': 'Guten Tag',
        'contact': 'Bei Fragen kontaktieren Sie uns unter {email}.',
        'regards': 'Mit freundlichen Grüssen,',
        'team': 'Das {name}-Team',
        'footer': '{name} - Fahrzeugvermietung in der Schweiz',
        'docs_title': 'Vorzulegende Pflichtdokumente',
        'docs_id': 'Physischer Personalausweis (Original, gültig)',
        'docs_license': 'Physischer Führerschein (Original, gültig)',
        'docs_warning': 'Ohne diese Dokumente kann Ihnen das Fahrzeug nicht übergeben werden.',
        'cat_label': 'Kategorie',
        'pickup': 'Abholdatum',
        'ret': 'Rückgabedatum',
        'duration': 'Dauer',
        'days': 'Tag(e)',
        'location_label': 'Ort',
        'total': 'Gesamtbetrag',
        'conf_header': 'Buchungsbestätigung',
        'conf_title': 'Buchung Bestätigt',
        'conf_text': 'Wir freuen uns, Ihre Buchung zu bestätigen. Wir garantieren Ihnen das reservierte Fahrzeug oder ein gleichwertiges Fahrzeug derselben Kategorie.',
        'cash_note': 'Die Zahlung erfolgt in bar bei der Fahrzeugübernahme.',
        'conf_subject': 'Buchung bestätigt - {v} | LogiRent',
        'req_header': 'Buchungsanfrage',
        'req_title': 'Buchungsanfrage erhalten',
        'req_text': 'Wir haben Ihre Buchungsanfrage erhalten. Unser Team wird sie prüfen und Ihnen so schnell wie möglich eine Bestätigung senden.',
        'req_pending': 'Ihre Buchung wartet auf die Bestätigung durch unser Team. Sie erhalten eine E-Mail, sobald sie validiert wurde.',
        'req_subject': 'Buchungsanfrage erhalten - {v} | LogiRent',
        'offer_header': 'Buchungsangebot',
        'offer_sub': 'Die Agentur unterbreitet Ihnen ein Angebot für Ihre Anfrage',
        'offer_text': 'Nach Prüfung Ihrer Anfrage sendet Ihnen unsere Agentur ein Angebot für die Buchung des <strong>{v}</strong>.',
        'offer_new_price': 'Neuer vorgeschlagener Preis',
        'offer_msg_label': 'Nachricht der Agentur',
        'offer_accept': 'Um <strong>dieses Angebot anzunehmen</strong>, melden Sie sich in Ihrem LogiRent-Konto an. Wenn Sie nicht fortfahren möchten, können Sie diese Nachricht ignorieren.',
        'offer_subject': 'Buchungsangebot - {v} - CHF {p:.2f} | LogiRent',
        'pay_header': 'Zahlungsbestätigung',
        'pay_title': 'Zahlung Bestätigt',
        'pay_text': 'Wir bestätigen den Erhalt Ihrer Zahlung. Ihre Buchung ist nun vollständig validiert.',
        'pay_badge': 'Zahlung erhalten - Buchung validiert',
        'pay_subject': 'Zahlung bestätigt - {v} | LogiRent',
        'rem_header': 'Erinnerung - Miete morgen',
        'rem_title': 'Erinnerung - Ihre Miete beginnt morgen',
        'rem_text': 'Wir erinnern Sie daran, dass Ihre Miete <strong>morgen am {d}</strong> beginnt.',
        'rem_location': 'Abholort: <strong>{loc}</strong>',
        'rem_location_missing': 'Der Abholort wird Ihnen von Ihrer Agentur mitgeteilt.',
        'rem_subject': 'Erinnerung: Ihre Miete des {v} beginnt morgen | LogiRent',
        'st_header': 'Aktualisierung Ihrer Buchung',
        'st_confirmed_title': 'Buchung Bestätigt',
        'st_confirmed_msg': 'Ihre Buchung für <strong>{v}</strong> wurde bestätigt.',
        'st_active_title': 'Miete Läuft',
        'st_active_msg': 'Ihre Miete des <strong>{v}</strong> ist jetzt aktiv. Gute Fahrt!',
        'st_completed_title': 'Miete Beendet',
        'st_completed_msg': 'Ihre Miete des <strong>{v}</strong> ist beendet. Vielen Dank für Ihr Vertrauen!',
        'st_cancelled_title': 'Buchung Storniert',
        'st_cancelled_msg': 'Ihre Buchung für <strong>{v}</strong> wurde storniert.',
        'st_update_title': 'Aktualisierung',
        'st_update_msg': 'Der Status Ihrer Buchung wurde aktualisiert.',
        'st_confirmed_subject': 'Buchung bestätigt - {v}',
        'st_active_subject': 'Miete läuft - {v}',
        'st_completed_subject': 'Miete beendet - {v}',
        'st_cancelled_subject': 'Buchung storniert - {v}',
        'st_update_subject': 'Buchungsaktualisierung - {v}',
        'veh_label': 'Fahrzeug',
        'from_label': 'Von',
        'to_label': 'Bis',
        'amount_label': 'Betrag',
        'wel_subject': 'Willkommen bei {name} - Ihre Zugangsdaten',
        'wel_sub': 'Willkommen auf unserer Vermietungsplattform',
        'wel_text': 'Ihr Konto wurde erfolgreich von <strong>{name}</strong> erstellt. Sie können sich jetzt anmelden, um unsere verfügbaren Fahrzeuge zu durchsuchen und Buchungen vorzunehmen.',
        'wel_creds': 'Ihre Zugangsdaten',
        'wel_email': 'E-Mail',
        'wel_pass': 'Passwort',
        'wel_change': 'Wir empfehlen Ihnen, Ihr Passwort nach der ersten Anmeldung zu ändern.',
        'wel_login': 'Jetzt anmelden',
        'wel_mobile': 'Mobile App',
        'wel_scan': 'Scannen Sie diesen QR-Code, um auf die App zuzugreifen',
        'wel_contact': 'Bei Fragen zögern Sie nicht, uns zu kontaktieren.',
        'wel_footer': '{name} — Fahrzeugvermietung',
        'ct_header': 'Mietvertrag unterzeichnet',
        'ct_title': 'Vertrag Erfolgreich Unterzeichnet',
        'ct_text': 'Ihr Mietvertrag <strong>Nr. {n}</strong> für das Fahrzeug <strong>{v}</strong> wurde erfolgreich unterzeichnet.',
        'ct_pdf_text': 'Den unterzeichneten Vertrag finden Sie als PDF im Anhang dieser E-Mail.',
        'ct_pdf_badge': 'Das Vertrags-PDF ist dieser E-Mail beigefügt',
    },
}


def tr(lang: str) -> dict:
    return T.get(lang if lang in T else 'fr', T['fr'])
